### ISSUE TITLE
fprettify...

### ISSUE THREAD

**Issue by semi-h** [xcompact3d/x3d2#22]
fprettify doesn't allow fine grained control over some of the whitespace preferences. Lets use this thread to list the "wrong" stuff fprettify does.

- I start with the most important one. fprettify doesn't understand the chevron syntax 
`call gpu_kernel<<<blocks, threads>>>(arguments,...)`
and adds lots of spaces between `<` and `>`. Changing the settings for the whitespace around `<,>` messes up the if statements.

**Comment by Nanoseb** [comment]
adding mine:
- it sometimes doesn't handle indentation correctly in front of `write` statements. (see https://github.com/xcompact3d/x3d2/pull/19#discussion_r1423777778)


For now I have disabled my pre-commit hook which is a shame as it was neatly done.

**Comment by JamieJQuinn** [comment]
Fixed by #31
