### ISSUE TITLE
fprettify alternatives

### ISSUE THREAD

**Issue by Nanoseb** [xcompact3d/x3d2#23]
Since #22 is listing problems facing with fprettify. I am creating an other issue see what else is around.

https://fortranwiki.org/fortran/show/Tools is likely a good starting point. In particular

- [findent](https://sourceforge.net/projects/findent/): indentation only, but seems to work well, still active development
- [fortran-linter](https://github.com/cphyc/fortran-linter): fixes a handful of simple syntax issues, mainly space related (not tested yet), still active development
- [flint](https://gitlab.com/cerfacs/flint): only to check a syntax

**Comment by semi-h** [comment]
Because we have decided to go ahead with fprettify the issue can be closed.
