### ISSUE TITLE
Reordering operations

### ISSUE THREAD

**Issue by Nanoseb** [xcompact3d/x3d2#42]
Need reordering steps from:

- x -> y
  - [x] cuda
  - [ ] omp
- x -> z
  - [x] cuda
  - [ ] omp
- y -> x
  - [x] cuda
  - [ ] omp
- y -> z
  - [x] cuda
  - [ ] omp
- z -> x
  - [ ] cuda
  - [ ] omp
- z -> y
  - [x] cuda
  - [ ] omp

~~Note: z -> x is not required as of 19/02/2024.~~

Curl operator requires z -> x, 27/02/2024.

**Comment by pbartholomew08** [comment]
Based on #48 I think that once this issue is complete that it should be possible to remove `-Wno-unused-dummy-arguments` from the GNU debug flags as I think many cases which necessitated it were stub implementations of the rotations.
