### ISSUE TITLE
Implement OMP backend for basic math operators

### ISSUE THREAD

**Issue by CFD-Xing** [xcompact3d/x3d2#93]
Currently OMP backend for basic math operators such as `vecadd` is not yet implemented. OMP backend implementation is necessary for testing of the time integrator, for example.

**Comment by pbartholomew08** [comment]
Just to check, the missing operators are:
1) `sum_<y|z>intox`
2) `vecadd`
3) `scalar_product`
?

Happy to take a turn at this - is there anything else missing?

**Comment by semi-h** [comment]
I think these are all the basic ones missing. The only thing to keep in mind is reorder interface in the OpenMP backend do not support reorderings to and from cartesian data structure yet. If you're using get_field_data or set_field_data they require these currently unsupported reordering directions with their default arguments.

**Comment by Nanoseb** [comment]
> The only thing to keep in mind is reorder interface in the OpenMP backend do not support reorderings to and from cartesian data structure yet. If you're using get_field_data or set_field_data they require these currently unsupported reordering directions with their default arguments.

Ah yes, I realised that the other day. I am going to implement it as that's indeed missing and should be easy to do.

**Comment by Nanoseb** [comment]
see #101 for the reordering ones

**Comment by pbartholomew08** [comment]
Closed by #103
